### ISSUE TITLE
EnsureModule does not regenerate gen_py if it gets corrupted.

### ISSUE THREAD

**Issue by dsmitran** [mhammond/pywin32#1923]
## Description

We have multiple tools that are using win32com to work with Excel using EnsureDispatch or Dispatch.
Ever since switching to Python 3 we get multiple support request each week that the excel communication is not working.

We think it might be because the gen_py cache got corrupt and the Rebuild did not happen correctly.
Most of the time the gen_py subdir is empty.
We think that the corruption might happen since multiple applications are running simultaneously and that one holds the lock on the gen_py subdir while the other tries to regenerate the cache.

One other reason might be that shutil.rmtree is not a synchronous call.

### test_ensure_module.py

```python
import distutils.sysconfig
import os
import shutil
import sys

import win32com


gen_py_dir = win32com.__gen_path__


def CleanDir(path):
    if os.path.exists(path):
        for root, dirs, files in os.walk(path):
            for f in files:
                os.unlink(os.path.join(root, f))
            for d in dirs:
                shutil.rmtree(os.path.join(root, d))


def CallEnsureDispatch():
    print("import win32com.client")
    import win32com.client as cl
    print("Call: gencache.EnsureDispatch('Excel.Application')")
    cl.gencache.EnsureDispatch('Excel.Application')
    print("WORKS: gencache.EnsureDispatch('Excel.Application')")


def main():
    print(sys.version)

    site_packages = distutils.sysconfig.get_python_lib(plat_specific=1)
    print("pywin32.version: %s" % open(os.path.join(site_packages, "pywin32.version.txt")).read().strip())
    print("=" * 64)

    print("CleanDir(%s)" % gen_py_dir)
    CleanDir(gen_py_dir)

    make_dir = os.path.join(gen_py_dir, "00020813-0000-0000-C000-000000000046x0x1x9")
    print("os.makedirs(%s)" % make_dir)
    os.makedirs(make_dir)

    CallEnsureDispatch()


if __name__ == "__main__":
    main()
```

### Python 2.7

```
>> python test_ensure_module.py

2.7.17 (default, Oct 28 2019, 21:35:07) [MSC v.1500 64 bit (AMD64)]
pywin32.version: 221
================================================================
CleanDir(C:\Users\<USER>\AppData\Local\Temp\gen_py\2.7)
os.makedirs(C:\Users\<USER>\AppData\Local\Temp\gen_py\2.7\00020813-0000-0000-C000-000000000046x0x1x9)
import win32com.client
Rebuilding cache of generated files for COM support...
Checking 00020813-0000-0000-C000-000000000046x0x1x9
Could not add module (IID('{00020813-0000-0000-C000-000000000046}'), 0, 1, 9) - <type 'exceptions.ImportError'>: No module named 00020813-0000-0000-C000-000000000046x0x1x9
Done.
Call: gencache.EnsureDispatch('Excel.Application')
WORKS: gencache.EnsureDispatch('Excel.Application')
```

Why does it work in Python 2.7?:

win32com\client\gencache._GetModule:
 * raises ImportError
 
### Python 3.10

```
>> python test_ensure_module.py

3.10.2 | packaged by conda-forge | (main, Mar  8 2022, 15:47:33) [MSC v.1929 64 bit (AMD64)]
pywin32.version: 303
================================================================
CleanDir(C:\Users\<USER>\AppData\Local\Temp\gen_py\3.10)
os.makedirs(C:\Users\<USER>\AppData\Local\Temp\gen_py\3.10\00020813-0000-0000-C000-000000000046x0x1x9)
import win32com.client
Rebuilding cache of generated files for COM support...
Checking 00020813-0000-0000-C000-000000000046x0x1x9
Could not add module (IID('{00020813-0000-0000-C000-000000000046}'), 0, 1, 9) - <class 'AttributeError'>: module 'win32com.gen_py.00020813-0000-0000-C000-000000000046x0x1x9' has no attribute 'CLSIDToClassMap'
Done.
Call: gencache.EnsureDispatch('Excel.Application')
Traceback (most recent call last):
  File "test_ensure_module.py", line 47, in <module>
    main()
  File "test_ensure_module.py", line 43, in main
    CallEnsureDispatch()
  File "test_ensure_module.py", line 25, in CallEnsureDispatch
    cl.gencache.EnsureDispatch('Excel.Application')
  File "env\.py3_conda\test_excel_com\lib\site-packages\win32com\client\gencache.py", line 626, in EnsureDispatch
    mod = EnsureModule(tla[0], tla[1], tla[3], tla[4], bForDemand=bForDemand)
  File "env\.py3_conda\test_excel_com\lib\site-packages\win32com\client\gencache.py", line 522, in EnsureModule
    module.MinorVersion != tlbAttributes[4]
AttributeError: module 'win32com.gen_py.00020813-0000-0000-C000-000000000046x0x1x9' has no attribute 'MinorVersion'
```

#### Why does it not work in Python 3.10

win32com\client\gencache._GetModule
 * does not raise ImportError
 * it returns:
 ** <module 'win32com.gen_py.00020813-0000-0000-C000-000000000046x0x1x9' (<_frozen_importlib_external._NamespaceLoader object at 0x00000295C7110A90>)>

PEP 382 – Namespace Packages: 

 * https://peps.python.org/pep-0382/

### Proposed solution

Check if we have a valid loader (if a module can be imported)
 * https://docs.python.org/3/library/importlib.html#checking-if-a-module-can-be-imported

```python
def _GetModule(fname):
    """Given the name of a module in the gen_py directory, import and return it."""
    mod_name = "win32com.gen_py.%s" % fname

    spec = importlib.util.find_spec(mod_name)
    # spec is None:
    # * if __gen_path__ is empty
    # * or if the __gen_path__/subpackage does not exist
    # spec.loader is None: if we don't have any __init__.py inside
    # * __gen_path__/subpackage
    # Since it has no __init__.py it's loaded as a Namespace:
    #  * ModuleSpec(loader=None, submodule_search_locations=_NamespacePath)
    # Normally we expect the loader to be of type:
    #  * _frozen_importlib_external.SourceFileLoader
    if spec is None or spec.loader is None:
        raise ImportError(f"Could not find module: {mod_name}")

    mod = __import__(mod_name)
    return sys.modules[mod_name]
```

**Comment by mhammond** [comment]
I wonder if the correct solution is to add locking? Having multiple processes race over this directory seems like it's going to cause many problems that are difficult to anticipate, with this being just one?

**Comment by dsmitran** [comment]
We are currently using a workaround since October 2022 for our use case. Ever since the issue has not been reported back from our users.

We are using cx_freeze to freeze our application.

The workaround is:

- never ever put win32com **outside** library.zip when freezing (reason: Dispatch and DispatchEx do not use the cache in this case)
- never ever use EnsureDispatch
- we have created a copy of the generated constants (this way we don't need EnsureDispatch)

**Comment by dsmitran** [comment]
Using a lock would not fix the issue that **_GetModule** if not working correctly.

**Update**: Before the workaround we have experienced the issue even when running a single application.

**Comment by tonyroberts** [comment]
> I wonder if the correct solution is to add locking? Having multiple processes race over this directory seems like it's going to cause many problems that are difficult to anticipate, with this being just one?

I've been looking into this as it causes problems when using EnsureDispatch from multiple concurrent processes where the gen_py files haven't yet been created.

There is a mutex used when writing the files and when attempting to import the module, but the issue is that when generating the module the directory is created and a temporary file is written to that folder before the mutex is acquired (which happens when renaming the temporary file to the final module).

Acquiring the mutex in GenerateFromTypeLibSpec earlier, before the folder is created, resolves the issue. But, I'm assuming that generating the temporary file is done without the mutex being held intentionally? Perhaps so that generating child modules in GenerateChildFromTypeLibSpec doesn't block importing the main module?

One solution would be to change the temporary path used to different and not create the package directory without the mutex acquired. Alternatively, checking if the imported module is a namespace package or not in _GetModule would also fix the issue.

**Comment by mhammond** [comment]
IIRC, it tries to generate object definitions as they are needed, rather than generating every single object in the type library.
