### ISSUE TITLE
win32com.mapi.mapi missing in 3.1 release?

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#465]
I'm just a Python newbie so forgive me, if I did something wrong.

The demo mapisend.py works fine using the 2.6 release, but using the 3.1 release I get the error below.
I also noticed that the library mapi.pyd ist missing in 3.1.

PythonWin 3.1.1 \(r311:74483, Aug 17 2009, 17:02:12\) \[MSC v.1500 32 bit \(Intel\)\] on win32.
Portions Copyright 1994-2008 Mark Hammond - see 'Help/About PythonWin' for further copyright information.
Traceback \(most recent call last\):
File "C:\dev\Python31\Lib\site-packages\pythonwin\pywin\framework\scriptutils.py", line 322, in RunScript
debugger.run\(codeObject, \_\_main\_\_.\_\_dict\_\_, start\_stepping=0\)
File "C:\dev\Python31\Lib\site-packages\pythonwin\pywin\debugger\\\_\_init\_\_.py", line 60, in run
\_GetCurrentDebugger\(\).run\(cmd, globals,locals, start\_stepping\)
File "C:\dev\Python31\Lib\site-packages\pythonwin\pywin\debugger\debugger.py", line 655, in run
exec\(cmd, globals, locals\)
File "C:\dev\PyMAPIAddMailbox\mapisend.py", line 9, in &lt;module&gt;
from win32com.mapi import mapi
ImportError: cannot import name mapi
&gt;&gt;&gt; from win32com.mapi import mapi
Traceback \(most recent call last\):
File "&lt;interactive input&gt;", line 1, in &lt;module&gt;
ImportError: cannot import name mapi
&gt;&gt;&gt; from win32com.mapi import mapitags
&gt;&gt;&gt; 

Reported by: asklucas

Original Ticket: [pywin32/bugs/465](https://sourceforge.net/p/pywin32/bugs/465)
