### ISSUE TITLE
unable to compile with python 3.11

### ISSUE THREAD

**Issue by Battant** [mhammond/pywin32#1716]
Actuel result ;

win32/src/PyUnicode.cpp(144): error C3861: 'PyUnicode_EncodeMBCS' : unkown identifier

* Steps to reproduce the problem.
* clone python 3.11 repository
* https://github.com/python/cpython
* Build 
* Try to build pywin32 with it

* Version of Python and pywin32
* python3.11 commit 4a42cebf6dd769e2fa4e234a9e91093b3ad1cb63 (HEAD -> main, origin/main, origin/HEAD)
* pywin32 commit 1816ac672bdf8a5fe06cee0f7bd387de97f35b98 

PyUnicode_EncodeMBCS was removed from python on May 7th 2021 by bpo-44029

Best regards

Battant

**Comment by mhammond** [comment]
Thanks - fixed in e6f7299838b937b081672f5142c1a6a2f3a077f5

**Comment by pawamoy** [comment]
Do you have an ETA for a Python 3.11 compatible wheel published on PyPI.org :slightly_smiling_face:?

**Comment by pawamoy** [comment]
I see you just published v303, thanks!
