### ISSUE TITLE
unable to compile with pypy 3.7-v.7.3.7-win64

### ISSUE THREAD

**Issue by jaegunjung** [mhammond/pywin32#1790]
Actual Result,

win32/src/PyUnicode.cpp(110): error C3861: 'PyUnicode_EncodeCodePage': identifier not found

Step to reproduce the problem.

1. https://downloads.python.org/pypy/pypy3.8-v7.3.7-win64.zip
2. Extract it and copy pypy3.8-v7.3.7-win64 to C:\Program Files
3. Add C:\Program Files\pypy3.8-v7.3.7-win64 in PATH
4. pypy3.exe -m ensurepip
5. pypy3.exe setup.py install

Best Regards,
Jaegun Jung

**Comment by mhammond** [comment]
I've no idea what https://downloads.python.org/pypy/pypy3.8-v7.3.7-win64.zip is. Everything builds fine in official Python builds.
